require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.4.3
  DisplayCopNames: true
  Exclude:
    - '**/Guardfile'
    - 'bin/**/*'
    - 'config/deploy/*'
    - 'config/environments/*'
    - 'db/**/*'
    - 'tmp/**/*'
    # deploy
    - Capfile
    # spec rubocop will be restored later
    - 'spec/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Naming/FileName'

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 80

Metrics/ModuleLength:
  Enabled: false

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Enabled: false

# The guiding principle of classes is SRP, SRP can't be accurately measured
# by LoC
Metrics/ClassLength:
  Max: 1550

# Refactor to remove this issues
Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false
